# Generated by Django 4.2.16 on 2024-09-08 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlamentares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='parlamentares',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parlamentares'),
            preserve_default=False,
        ),
    ]
