# Generated by Django 4.2.16 on 2024-09-08 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parlamentares_acompanhante_parlamentares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompanhante',
            old_name='parlamentares',
            new_name='parlamentare',
        ),
    ]
