# Generated by Django 4.2.16 on 2024-09-09 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_acompanhante_parlamentare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhante',
            name='parlamentares',
        ),
        migrations.AddField(
            model_name='acompanhante',
            name='parlamentare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.parlamentares'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
