# Generated by Django 4.2.16 on 2024-09-09 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_acompanhante_parlamentares_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompanhante',
            old_name='parlamentare',
            new_name='parlamentares',
        ),
    ]
